Fix visibility setting to ViewVisibility
ForesightMiningSoftwareCorporation/bevy_infinite_grid pull request #49
Opened 2024-02-22 09:11 UTC by luca-della-vedova

Hello!

In the migration to 0.12 in #43, there was a mistake [here](https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/pull/43/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L248-R249) where a `ComputedVisibility.set_visible_in_view()` was migrated to a setting to `InheritedVisibility`.
This resulted in the plugin breaking all hierarchical visibility propagations as soon as a grid is spawned, making everything always visible at all times.
In this PR I changed it to what it should have been migrated to, which is a setting to `ViewVisibility`.

CC @pcwalton  just for a sanity check

2024-02-22 17:54 UTC, ThomasAlban commented
Thank god, tracking down that it was this crate rather than an error in my code took me ages to find!

2024-02-22 18:47 UTC, IceSentry requested changes
Thank you! We are in the process of updating to 0.12 so we haven't used the crate yet in practice.

Can you bump the patch version in the cargo.toml? This will trigger CI to release the updated version

2024-02-22 19:04 UTC, pcwalton commented
LGTM

2024-02-23 01:56 UTC, luca-della-vedova commented
Bumped the patch version!

> Thank god, tracking down that it was this crate rather than an error in my code took me ages to find!

I hear you! It took me several days, a plea for help in Discord and digging all the way into `bevy_hierarchy` to finally figure it out, it really was a journey

2024-02-23 04:19 UTC, IceSentry approved these changes

2024-02-23 06:39 UTC, IceSentry commented
Welp, looks like bumping from a branch of someone that isn't an owner of the crate doesn't work with our CI. I'll revert the commit and bump it myself. Sorry about that.

2024-02-23 07:30 UTC, merged

2024-02-23 09:56 UTC, luca-della-vedova commented
Thanks for the quick review! Can you folks push a patch release to crates.io? I would almost consider yanking the previous version since the bug is pretty severe but I'll leave the choice up to you!

2024-05-09 19:52 UTC, IceSentry commented
Hey, very sorry about that, we had CI issues and I never realized that a version with this fix was never published. I just published it so now 0.10.1 has the fix and is compatible with bevy 0.12.

In the bevy 0.13 version of this crate we just removed the shadow feature because it was causing too many issues like this.